#:schema node_modules/wrangler/config-schema.json
name = "email-handler"
main = "src/index.ts"
compatibility_date = "2025-05-05"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/
[placement]
mode = "smart"

# Bind a D1 Database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "email-db"
database_id = "074a2cf1-4e48-478e-b3f5-5665690d6601" # <-- Replace with your actual D1 Database ID
